# Generated by Django 5.2.6 on 2025-09-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.DecimalField(decimal_places=0, max_digits=10)),
                ('idP', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit')),
                ('idR', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rayon', to='monApp.rayon')),
            ],
        ),
    ]
