# Generated by Django 5.2.6 on 2025-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_produit_datefabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStat', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
    ]
