# Generated by Django 5.2.6 on 2025-09-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_produit_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statut',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='status',
        ),
        migrations.AddField(
            model_name='produit',
            name='Statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Statut', to='monApp.statut'),
        ),
    ]
