# Generated by Django 5.2.6 on 2025-09-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_rename_status_statut_remove_produit_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Statut',
            new_name='idStatus',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='idStat',
            new_name='idStatus',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='libelle',
            new_name='libelleStatus',
        ),
    ]
