# Generated by Django 5.2.5 on 2025-09-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_rename_statut_produit_idstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='dateFabrication',
            new_name='dateFabProd',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='idStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='idStatus',
            new_name='idStatut',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='libelleStatus',
            new_name='libelleStatut',
        ),
    ]
