# Generated by Django 5.2.5 on 2025-09-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_rename_datefabrication_produit_datefabprod_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('idP', 'idR')},
        ),
    ]
